
#Settings for the mechanical sifter
[sifter]
	#Stress impact
	#Range: 0.0 ~ 64.0
	stressImpact = 4.0
	#Output item capacity
	#Range: > 1
	outputCapacity = 16
	#Minimum required speed
	#Range: 0.0 ~ 254.0
	minimumSpeed = 1.0

